### ISSUE TITLE
float object cannot be interpreted as integer

### ISSUE THREAD

**Issue by tconlin** [Reenforcements/PES-Embroidery#1]
$ ./run-tests.sh
```
...
....more of the same error output...
....
Closest color: (21, 'Ultramarine', 0, 28, 223)
Performing up to 302 intersections along path: Line(start=(70.040118+560.337548110686j), end=(603.6237102703919+26.75395584029411j))
(From (70.040118+560.337548110686j) to (603.6237102703919+26.75395584029411j))
Traceback (most recent call last):
  File "../src/main.py", line 57, in <module>
    levels = makeStitchLevels(shape, fillColor, debug=args.debug, slope=(-args.slope), threadWidth=threadWidth)
  File "/home/taylor/dev/PES-Embroidery/src/svgFunctions.py", line 199, in makeStitchLevels
    for i in range(0, len( intersectionPoints ) / 2):
TypeError: 'float' object cannot be interpreted as an integer
```
$

**Comment by Reenforcements** [comment]
@tconlin Thanks for opening an issue. I neglected to mention that the program should be run using Python 2.7. I updated the README.md. Please let me know if using Python 2.7 fixes it for you.

**Comment by tconlin** [comment]
@Reenforcements Works perfectly now. I've been looking around for a svg2pes tool, and this has produced, by far, the best results. Great job!

**Comment by Reenforcements** [comment]
@tconlin Thanks! I'm glad it works for you now.
